Jf 12 Add BottomNavigationView
Evgeniy-Kov/JobFinder pull request #13
Opened 2024-12-08 16:27 UTC by OlgaRumRum

2024-12-08 18:35 UTC, XroMSPb requested changes

2024-12-08 18:35 UTC, XroMSPb commented on app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
> +                }
Предлагаю объединить фрагменты для большей наглядности
```kotlin
                R.id.settingFilterFragment,
                R.id.placeOfWorkFragment,
                R.id.countryFragment,
                R.id.regionFragment,
                R.id.vacancyFragment -> {
                    changeBottomNavigationViewVisibility(false)
                }
```

2024-12-09 10:54 UTC, Evgeniy-Kov approved these changes

2024-12-09 11:12 UTC, XroMSPb approved these changes

2024-12-09 11:14 UTC, merged