JF-6  Создан экран команды
Evgeniy-Kov/JobFinder pull request #15
Opened 2024-12-08 18:46 UTC by Maksim-Isaev

2024-12-09 09:55 UTC, XroMSPb requested changes

2024-12-09 09:55 UTC, XroMSPb commented on app/src/main/res/values/dimens.xml
> +
Так же лишние строки

2024-12-09 09:55 UTC, XroMSPb commented on app/src/main/res/layout/fragment_team.xml
>  <?xml version="1.0" encoding="utf-8"?>
А у тебя точно стоит реформат код при комите? 
![image](https://github.com/user-attachments/assets/12182e9b-f1ce-48ab-a097-6f3936016d5e)
Проверь пожалуйста

2024-12-09 11:05 UTC, Evgeniy-Kov requested changes

2024-12-09 11:05 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +            android:layout_marginBottom="16dp"
margin нужно вынести в ресурсы

2024-12-09 11:05 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +            android:layout_marginBottom="16dp"
margin нужно вынести в ресурсы

2024-12-09 11:05 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +            android:layout_marginBottom="16dp"
margin нужно вынести в ресурсы

2024-12-09 11:05 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +        android:layout_height="56dp"
Нужно вынести в ресурсы

2024-12-09 11:05 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +        android:layout_height="110dp"
Нужно вынести в ресурсы

2024-12-09 11:05 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +            android:layout_marginBottom="16dp"
margin нужно вынести в ресурсы

2024-12-09 11:58 UTC, Evgeniy-Kov commented
![image](https://github.com/user-attachments/assets/fe767d10-4da7-472f-bd2b-f7a2d9d3900a)

Есть расхождения с макетом

2024-12-09 12:14 UTC, Evgeniy-Kov requested changes

2024-12-09 18:23 UTC, Maksim-Isaev commented on app/src/main/res/values/styles.xml
> +
done

2024-12-10 08:52 UTC, Evgeniy-Kov requested changes

2024-12-10 08:52 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +        android:layout_height="@dimen/dp_110"
`android:layout_height="wrap_content"`

2024-12-10 08:52 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +        android:paddingHorizontal="@dimen/dp_16">
Нужно добавить `android:layout_marginTop="@dimen/dp_24"`

2024-12-10 08:52 UTC, Evgeniy-Kov commented on app/src/main/res/layout/fragment_team.xml
> +        android:layout_marginTop="@dimen/dp_6"
`android:layout_marginTop="@dimen/dp_32"`

2024-12-10 18:14 UTC, Evgeniy-Kov approved these changes

2024-12-10 19:54 UTC, XroMSPb approved these changes

2024-12-10 20:07 UTC, merged